global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['{{ groups["monitoring"][0] }}:9100']
        labels:
          instance: node-exporter

  - job_name: 'prometheus'
    static_configs:
      - targets: ['{{ groups["monitoring"][0] }}:9090']
        labels:
          instance: prometheus

  - job_name: "flask"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "{{ groups['appserver1'][0] }}:8000"
          - "{{ groups['appserver2'][0] }}:8000"
        labels:
          instance: flask

  - job_name: "nginx"
    metrics_path: /prometheus
    static_configs:
      - targets: ['{{ groups["loadbalancer"][0] }}:9113']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["{{ groups['monitoring'][0] }}:9093"]

rule_files:
  - rules.yml