FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
#COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py Makefile .pylintrc pytest.ini test.sh ./

ENV FLASK_APP microblog.py

RUN <<-EOF
    chmod +x test.sh
    pip install -r requirements/test.txt
EOF

ENTRYPOINT ["./test.sh"]
