FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
#COPY app app
COPY migrations migrations
COPY requirements requirements
COPY Makefile ./
COPY ./requirements/test.txt microblog.py docker/test.sh ./

ENV FLASK_APP microblog.py

RUN <<-EOF
    python -m venv .venv
    .venv/bin/pip3 install -r test.txt
    chmod +x test.sh
    chown -R microblog:microblog ./
EOF

ENTRYPOINT ["./test.sh"]
