FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py docker/boot.sh ./

ENV FLASK_APP=microblog.py

RUN <<-EOF
    python -m venv .venv
    .venv/bin/pip3 install -r requirements.txt
    chmod +x boot.sh
    chown -R microblog:microblog ./
    apk upgrade --no-cache libcrypto3
    apk upgrade --no-cache libexpat
EOF

USER microblog

HEALTHCHECK --interval=10m --timeout=10s \
 CMD wget --quiet --tries=1 --spider http://localhost:5000/ || exit 1

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
