FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
#COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py Makefile .pylintrc pytest.ini test.sh ./

ENV FLASK_APP microblog.py

RUN <<-EOF
    apk add --no-cache make=4.3-r0 gcc=10.2.1_pre1-r3 musl-dev=1.2.2-r0
    chmod +x test.sh
    pip install --no-cache-dir -r requirements/test.txt
EOF

ENTRYPOINT ["./test.sh"]
