---
- name: Start MySql container
  docker_container:
    name: mysql
    image: mysql:5.7
    command: "--default-authentication-plugin=mysql_native_password"
    env:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "microblog"
      MYSQL_ROOT_PASSWORD: "microblog"
    volumes:
      - ./data/mysql:/var/lib/mysql
    state: started
    restart_policy: always
    published_ports:
      - "3306:3306"
