---
- name: Install packages
  apt:
    name: "{{ packages}}"
    state: present

- name: Check if cert is created
  stat:
    path: /etc/letsencrypt/live/{{ domain_name }}/cert.pem
  register: letsencrypt_cert

- debug: msg="{{ letsencrypt_cert.stat.exists }}"

- name: Stop ngingx
  service:
    name: nginx
    state: stopped
  when: not letsencrypt_cert.stat.exists

- name: Generate certificates for https
  shell: certbot certonly --standalone --non-interactive --expand --agree-tos --email {{ admin_email }} -d {{ domain_name }} -d www.{{ domain_name }}
  when: not letsencrypt_cert.stat.exists

- name: Stop ngingx
  service:
    name: nginx
    state: started
  when: not letsencrypt_cert.stat.exists

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create nginx site
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart nginx

- name: Create load-balancer.conf
  template:
    src: load-balancer.conf.j2
    dest: /etc/nginx/sites-available/load-balancer.conf
  notify:
    - Restart nginx

- name: Create symbolic link to enabled folder
  file:
    src: /etc/nginx/sites-available/load-balancer.conf
    dest: /etc/nginx/sites-enabled/load-balancer.conf
    state: link

- name: Start nginx prometheus exporter
  docker_container:
    name: prometheus-nginx-exporter
    image: nginx/nginx-prometheus-exporter:0.4.2
    state: started
    restart_policy: always
    ports:
      - "9113:9113"
    env:
      nginx_scrape_uri: "http://{{ domain_name }}/metrics"
      nginx_retries: "10"
      nginx_ssl_verify: "false"
      web_telemetry_path: "/prometheus"
    command: "--nginx.scrape-uri=http://{{ domain_name }}/metrics --nginx.retries=5 --nginx.ssl-verify=false --web.telemetry-path=/prometheus"
