# Created file for docker image publish workflow

name: Docker Publish Image

on:
  workflow_call: {}
#  push:
#    branches:
#      - '**'  # Trigger on push to any branch
#  pull_request:
#    branches:
#      - '**'  # Trigger on any pull request
  release:
    types: [created]
  
  
  
jobs:
  run-tests:
    uses: ./.github/workflows/test.yml  # This will trigger `test.yml`

  build-docker-image:
      needs: run-tests
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          
          - name: Build and push docker image for production
            uses: docker/build-push-action@v6
            env:
              DOCKER_CONTENT_TRUST: 1
            with:
              context: .
              file: ./docker/Dockerfile_prod
              push: true
              tags: susm20/microblog:${{ github.event.release.tag_name }}-prod

          - name: Build and push docker image for testing
            uses: docker/build-push-action@v6
            env:
              DOCKER_CONTENT_TRUST: 1
            with:
              context: .
              file: ./docker/Dockerfile_test
              push: true
              tags: susm20/microblog:${{ github.event.release.tag_name }}-test
          

