---
- name: Install Docker and Docker SDK for Python
  apt:
    name: docker.io
    state: latest

- name: Install pip3
  apt:
    name: python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
